#!/usr/bin/env bash

set -e

if pidof systemd
then
    cp /tmp/${npm_package_name}.service /etc/systemd/system/

    sudo systemctl enable ${npm_package_name}.service
    sudo systemctl start ${npm_package_name}.service
    sudo systemctl status ${npm_package_name}.service

    exit 0
fi

echo "No compatible init system was found"

# pidof /sbin/init && echo "sysvinit" || echo "other"